name: srt
description: List of sort ordering for our App.
version: 1.0.0
repository: https://github.com/dwyl/sort

environment:
  sdk: '>=2.19.2 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
